global using System;
global using System.Diagnostics;
global using System.Linq;
global using System.Threading.Tasks;
global using ObservableCollections;
global using R3;
global using RemoteLogViewer.Utils;
global using RemoteLogViewer.Utils.Attributes;
global using CommunityToolkit.Mvvm.DependencyInjection;